# Generated by Django 4.2.8 on 2024-02-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual_traffic_counting_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countingsession',
            name='date',
        ),
        migrations.AlterField(
            model_name='countingsession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='countingsession',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
