# Generated by Django 4.2.8 on 2024-02-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual_traffic_counting_app', '0003_cartype_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='countingsession',
            name='streams',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
