# Generated by Django 4.2.8 on 2024-02-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual_traffic_counting_app', '0004_countingsession_streams'),
    ]

    operations = [
        migrations.AddField(
            model_name='carcount',
            name='stream_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
