# Generated by Django 4.2.8 on 2024-02-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual_traffic_counting_app', '0005_carcount_stream_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='countingsession',
            name='car_types',
            field=models.ManyToManyField(blank=True, to='manual_traffic_counting_app.cartype'),
        ),
    ]
